# config/meta.yml

meta_product_name: "MaDoggo"
meta_title: "MaDoggo - A playful dog is a happy dog. Get your dog social."
meta_description: "A playful dog is a happy dog. Get your dog social."
meta_image: "dog-symbol.png" # should exist in `app/assets/images/`
twitter_account: "@product_twitter_account"   # required for Twitter Cards
